# apiVersion: apps.gitlab.com/v1beta1
# kind: GitLab
# metadata:
#   name: gitlab
#   namespace: gitlab-system
# spec:
#   chart:
#     version: 9.10.1
#     values:
#       global:
#         edition: ce
#         hosts:
#           domain: malef.lan
#         ingress:
#           configureCertmanager: false
#           provider: nginx
#           class: nginx
#           annotations:
#             cert-manager.io/cluster-issuer: ca-issuer
#         certificates:
#           customCAs:
#             - secret: ca-cert
#       installCertmanager: false
#       prometheus:
#         install: false
#       nginx-ingerss:
#         enabled: false
      