apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  annotations:
    argocd.argorpoj.io/sync-wave: "-1"
spec:
  project: default
  source:
    repoURL: https://charts.jetstack.io/
    targetRevision: 1.20.1
    chart: cert-manager
    helm:
      values: |
        prometheus: 
          enabled: true
          servicemonitor:
            enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true