apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-crds
  namespace: argocd
  annotations:
    argocd.argorpoj.io/sync-wave: "-15"
spec:
  project: default
  source:
    repoURL: https://github.com/LeoEliot/k8s-homelab.git
    targetRevision: main
    path: manifests/cert-manager-crds
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true