apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingresses
  namespace: argocd
  annotations:
    argocd.argorpoj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/LeoEliot/k8s-homelab.git
    targetRevision: main
    path: manifests/ingresses
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true