apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  ignoreDifferences:
  - group: "*"                     # Use wildcard for the core group
    kind: ConfigMap
    name: kube-prometheus-stack-grafana          # Specify the exact ConfigMap name
    jsonPointers:
      - /data                      # Ignore the entire 'data' section
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 82.15.1
    helm:
      valuesObject:
        crds:
          enabled: false
        prometheus:
          prometheusSpec:
            retention: 1d
  syncPolicy:
    syncOptions:
      - ClientSideApplyMigration=false
      - CreateNamespace=true
      - RespectIgnoreDifferences=true 
    automated: 
      prune: true
      selfHeal: true
    