apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-config-pvc
  namespace: media
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi  # Adjust based on your needs
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qbittorrent
  template:
    metadata:
      labels:
        app: qbittorrent
    spec:
      containers:
      - name: qbittorrent
        image: linuxserver/qbittorrent:latest
        env:
        - name: PUID
          value: "1000"  
        - name: PGID
          value: "1000"  
        - name: TZ
          value: "Europe/Moscow" 
        - name: WEBUI
          value: "8080"
        ports:
        - name: webui
          containerPort: 8080  
        - name: torrent-port
          containerPort: 6881
        - name: torrent-xudp
          containerPort: 6881
          protocol: UDP
        volumeMounts:
        - name: config
          mountPath: /config
        - name: media
          mountPath: /downloads  
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: qbittorrent-config-pvc
      - name: media
        hostPath:
          path: /home/malef/media
          type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: qbittorrent
  namespace: media
spec:
  selector:
    app: qbittorrent
  ports:
  - name: webui
    port: 8080
    targetPort: 8080
  - name: torrent-tcp
    port: 6881
    targetPort: 6881
  - name: torrent-udp
    port: 6881
    protocol: UDP
    targetPort: 6881
